//! CodeDB phase 1: wrap host-mrbc RITE output into typed envelopes and
//! emit an embeddable manifest module.
//!
//! Each source arrives as two independent mrbc compile passes; identical
//! bytes are required (the determinism gate the CodeDB caching story
//! depends on). The tool itself is pure Zig — no mruby state is created.

const std = @import("std");
const artifact = @import("artifact");
const artifact_config = @import("artifact_config");

pub fn main(init: std.process.Init) !u8 {
    const gpa = init.gpa;
    const io = init.io;
    var args = try std.process.Args.Iterator.initAllocator(init.minimal.args, gpa);
    _ = args.next() orelse return 1;
    const out_dir = args.next() orelse return fatal("missing output directory", .{});
    const cwd = std.Io.Dir.cwd();
    try cwd.createDirPath(io, out_dir);

    var output: std.Io.Writer.Allocating = .init(gpa);
    defer output.deinit();
    try output.writer.print(
        \\//! Generated by rite_envelope (CodeDB phase 1); do not edit.
        \\pub const Entry = struct {{ name: []const u8, bytes: []const u8 }};
        \\pub const entries = [_]Entry{{
        \\
    , .{});

    var count: usize = 0;
    while (args.next()) |name| {
        const pass_a = args.next() orelse return fatal("missing first compile pass", .{});
        const pass_b = args.next() orelse return fatal("missing second compile pass", .{});

        const a = try cwd.readFileAlloc(io, pass_a, gpa, .unlimited);
        defer gpa.free(a);
        const b = try cwd.readFileAlloc(io, pass_b, gpa, .unlimited);
        defer gpa.free(b);
        if (!std.mem.eql(u8, a, b)) {
            std.debug.print("rite_envelope: {s}: compile passes differ\n", .{name});
            return 1;
        }

        var image = try artifact.wrapRite(gpa, a, .{
            .compatibility = artifact_config.rite_compatibility_fingerprint,
        });
        defer image.deinit(gpa);

        const rite_path = try std.fs.path.join(gpa, &.{ out_dir, try std.fmt.allocPrint(gpa, "{s}.rite", .{name}) });
        defer gpa.free(rite_path);
        try cwd.writeFile(io, .{ .sub_path = rite_path, .data = image.encoded });
        try output.writer.print("    .{{ .name = \"{s}\", .bytes = @embedFile(\"{s}.rite\") }},\n", .{ name, name });
        count += 1;
    }
    if (count == 0) return fatal("no sources given", .{});
    try output.writer.writeAll("};\n");

    const manifest_path = try std.fs.path.join(gpa, &.{ out_dir, "manifest.zig" });
    defer gpa.free(manifest_path);
    try cwd.writeFile(io, .{ .sub_path = manifest_path, .data = output.writer.buffer[0..output.writer.end] });
    return 0;
}

fn fatal(comptime fmt: []const u8, values: anytype) u8 {
    std.debug.print("rite_envelope: " ++ fmt ++ "\n", values);
    return 1;
}
